### ISSUE TITLE
Insert text will become replace in code-editor

### ISSUE THREAD

**Issue by jwu** [fireball-packages/code-editor#4]
Is this known issues? When I try to insert text, it actually replace them.

**Comment by yorkie** [comment]
@jwu may I ask you to send a screenshot for this bug?

**Comment by jwu** [comment]
![screen shot 2015-08-20 at 4 08 12 pm](https://cloud.githubusercontent.com/assets/174891/9378662/b22a11c0-4755-11e5-9b5b-1937587dbe35.png)

you see, my cursor is after N[ode], when I type `f` it replace my `o`

![screen shot 2015-08-20 at 4 09 18 pm](https://cloud.githubusercontent.com/assets/174891/9378681/dadbd16c-4755-11e5-84b9-9fcdf680de56.png)

**Comment by jwu** [comment]
BTW, every time I open code-editor, console log shows:

```
param name missing: {RuntimeNode}: utils/api/engine-framework/editor/get-node-dump.js:273
param name missing: {RuntimeNode}: utils/api/engine-framework/runtime/wrappers/engine.js:243
param name missing: {RuntimeNode}: ../../fireball-projects/examples/build/engine-framework.js:8259
param name missing: {RuntimeNode}: ../../fireball-projects/examples/build/engine-framework.js:10238
param name missing: {RuntimeNode}: ../../fireball-projects/examples/build/Foobar/engine-framework.js:8715
param name missing: {RuntimeNode}: ../../fireball-projects/examples/build/Foobar/engine-framework.js:11520
param name missing: {RuntimeNode}: ../../fireball-projects/examples/build/examples/engine-framework.js:8259
param name missing: {RuntimeNode}: ../../fireball-projects/examples/build/examples/engine-framework.js:10238
param name missing: {RuntimeNode}: ../../fireball-projects/examples/temp/preview/engine-framework.js:8715
param name missing: {RuntimeNode}: ../../fireball-projects/examples/temp/preview/engine-framework.js:11520
```

Is this relative with the problem?

**Comment by yorkie** [comment]
They are not linked, this log just shows the warning when in parsing comment-based document by firedoc-api. Okay, let me have a try in the use case

**Comment by yorkie** [comment]
@jwu @nantas Hey do I need to bump a new version for applying my fix on the upstream fireball? Because I found nantas did it before. Anyway, this bug has been fixed at master, you feel free to make double check, thanks :)
